version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    env:
      REACT_APP_API_URL: http://146.190.244.35:3001/api
    ports:
      - 3000:3000

  backend: 
    depends_on: 
      - db
    build: ./backend
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
